openapi: "3.0.0"
info:
  description: "This is the Caps-API documentation."
  version: "1.0.0"
  title: "Swagger Caps Store"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "caps@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "item"
  description: "Everything about your Caps"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to Capstore orders"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
paths:
  /item:
    post:
      tags:
      - "item"
      summary: "Add a new item to the store"
      description: ""
      operationId: "addItem"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "item"
      summary: "Update an existing item"
      description: ""
      operationId: "updateItem"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Item not found"
        "405":
          description: "Validation exception"
  /order/findByStatus:
    get:
      tags:
      - "order"
      summary: "Finds Orders by status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "findOrdersByStatus"
      parameters:
      - name: "status"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Order"
        "400":
          description: "Invalid status value"
  /item/{itemId}:
    get:
      tags:
      - "item"
      summary: "Find item by ID"
      description: "Returns a single item"
      operationId: "getItemById"
      parameters:
      - name: "itemId"
        in: "path"
        description: "ID of item to return"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Item not found"
    put:
      tags:
      - "item"
      summary: "Updates a item in the store with form data"
      description: ""
      operationId: "updateItemWithForm"
      parameters:
      - name: "itemId"
        in: "path"
        description: "ID of item that needs to be updated"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"
    delete:
      tags:
      - "item"
      summary: "Deletes a item"
      description: ""
      operationId: "deleteItem"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        schema:
          type: "string"
      - name: "itemId"
        in: "path"
        description: "Item id to delete"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Item not found"
  /item/{itemId}/uploadImage:
    post:
      tags:
      - "item"
      summary: "uploads an image"
      description: ""
      operationId: "uploadFile"
      parameters:
      - name: "itemId"
        in: "path"
        description: "ID of item to update"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: string
  /store/inventory:
    get:
      tags:
      - "store"
      summary: "Returns item inventories by status"
      description: "Returns a map of status codes to quantities"
      operationId: "getInventory"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                additionalProperties:
                  type: "integer"
                  format: "int32"
  /store/order:
    post:
      tags:
      - "store"
      summary: "Place an order for a item"
      description: ""
      operationId: "placeOrder"
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: "Invalid Order"
  /store/order/{orderId}:
    get:
      tags:
      - "store"
      summary: "Find purchase order by ID"
      description: "For valid response try integer IDs with value >= 1 and <= 10.         Other values will generated exceptions"
      operationId: "getOrderById"
      parameters:
      - name: "orderId"
        in: "path"
        description: "ID of item that needs to be fetched"
        required: true
        schema:
          type: "integer"
          maximum: 10.0
          minimum: 1.0
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
    delete:
      tags:
      - "store"
      summary: "Delete purchase order by ID"
      description: "For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors"
      operationId: "deleteOrder"
      parameters:
      - name: "orderId"
        in: "path"
        description: "ID of the order that needs to be deleted"
        required: true
        schema:
          type: "integer"
          minimum: 1.0
          format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/User"
      responses:
        default:
          description: "successful operation"
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        schema:
          type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "string"
          headers:
            X-Rate-Limit:
              description: "calls per hour allowed by the user"
              schema:
                type: "integer"
                format: "int32"
            X-Expires-After:
              description: "date in UTC when token expires"
              schema:
                type: "string"
                format: "date-time"
        "400":
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /user/{username}:
    get:
      tags:
      - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "getUserByName"
      parameters:
      - name: username
        in: path
        required: true
        description: the user identifier, as username 
        schema:
          type: string
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
    put:
      tags:
      - "user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      parameters:
      - name: username
        in: path
        required: true
        description: the user identifier, as username 
        schema:
          type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "400":
          description: "Invalid user supplied"
        "404":
          description: "User not found"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
      parameters:
      - name: username
        in: path
        required: true
        description: the user identifier, as username 
        schema:
          type: string
      responses:
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
components:
  schemas:
    User:
        properties:
          id:
            type: integer
          name:
            type: string
    Item:
        properties:
          id:
            type: integer
          name:
            type: string
          price:
            type: number
          category:
            type: string
          descrition:
            type: string
          imageUrl:
            type: string
          stock: 
            type: number
          sizes: 
            allOf:
              - $ref: '#/components/schemas/Sizes'
          promotionalFlag:
            type: boolean
          promotionalPrice:
            type: number
    Sizes:
      type: array  
      items:
        type: string
    Order:
      properties:
        id:
          type: integer
        price:
          type: number
        dateCreated:
          type: string
        inPersonPickup:
          type: boolean
        expectedArrivalDate:
          type: string
        label:
          type: string
        trackingId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        status:
          type: string
        address:
          allOf:
            - $ref: '#/components/schemas/Address'
        userid:
          type: string
    Address:
      type: object
      properties:
        street1:
          type: string
        street2:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: number
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"